site_name: Project Docs
site_url: https://KongSoftwareSpain.github.io/projects-docs/
theme:
  name: material
  language: es

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - encryptcontent:
      global_password: GLOBAL_PASSWORD_PLACEHOLDER
      summary: "Esta página está protegida. Por favor, introduce la contraseña para ver el contenido."
      placeholder: "Contraseña"
      action_button: "Entrar"
      invalid_password_message: "Contraseña incorrecta."

nav:
  - Inicio: index.md
  - Proyecto Ejemplo:
      - Visión general: proyecto_ejemplo/index.md
      - Onboarding:
          - Introducción: proyecto_ejemplo/onboarding/intro.md
          - Entorno: proyecto_ejemplo/onboarding/entorno.md
      - Arquitectura:
          - Overview: proyecto_ejemplo/arquitectura/overview.md
          - Decisiones: proyecto_ejemplo/arquitectura/decisiones.md
      - Guías:
          - Convenciones: proyecto_ejemplo/guias/convenciones.md
      - Otros:
          - Recursos: proyecto_ejemplo/otros/recursos.md
  - Fichaje App:
      - Visión general: fichaje_app/index.md
      - Onboarding:
          - Introducción: fichaje_app/onboarding/intro.md
          - Entorno: fichaje_app/onboarding/entorno.md
      - Arquitectura:
          - Overview: fichaje_app/arquitectura/overview.md
          - Infraestructura: fichaje_app/arquitectura/infraestructura.md
          - Decisiones: fichaje_app/arquitectura/decisiones.md
      - Guías:
          - Convenciones: fichaje_app/guias/convenciones.md
      - Otros:
          - Recursos: fichaje_app/otros/recursos.md
  - BBDD Local:
      - Visión general: bbdd_local/index.md
      - Onboarding:
          - Introducción: bbdd_local/onboarding/intro.md
          - Entorno: bbdd_local/onboarding/entorno.md
      - Arquitectura:
          - Overview: bbdd_local/arquitectura/overview.md
      - Guías:
          - Convenciones: bbdd_local/guias/convenciones.md
      - Otros:
          - Recursos: bbdd_local/otros/recursos.md
  - POSMamiPosada TPV:
      - Visión general: mamiposada/index.md
      - Onboarding:
          - Introducción: mamiposada/onboarding/intro.md
          - Entorno: mamiposada/onboarding/entorno.md
      - Arquitectura:
          - Overview: mamiposada/arquitectura/overview.md
          - Decisiones: mamiposada/arquitectura/decisiones.md
      - Guías:
          - Convenciones: mamiposada/guias/convenciones.md
      - Otros:
          - Recursos: mamiposada/otros/recursos.md
